version: '3.8'
services:
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:6-alpine
    restart: unless-stopped
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_DIALECT: postgres
      DB_PORT: 5432
      DB_USER: app
      DB_PASS: app
      DB_NAME: app
      REDIS_URI: redis://redis:6379
      PORT: 8081
    depends_on:
      - db
      - redis
    ports:
      - "8081:8081"
  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"
volumes:
  db_data:
